/*
 * Copyright (c) 2012 - present Adobe Systems Incorporated. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

define({

    /**
     * Errors
     */

    // General file io error strings
    "GENERIC_ERROR"                     : "(Lỗi {0})",
    "NOT_FOUND_ERR"                     : "Tập tin/Thư mục không tồn tại.",
    "NOT_READABLE_ERR"                  : "Tập tin/Thư mục không thể truy cập.",
    "EXCEEDS_MAX_FILE_SIZE"             : "Tập tin lớn hơn {0} MB không thể truy cập được với {APP_NAME}.",
    "NO_MODIFICATION_ALLOWED_ERR"       : "Thư mục này không thể bị thay đổi.",
    "NO_MODIFICATION_ALLOWED_ERR_FILE"  : "Tập tin không thể bị thay đổi.",
    "CONTENTS_MODIFIED_ERR"             : "Tập tin đã bị thay đổi bởi Ứng dụng khác ngoài {APP_NAME}.",
    "UNSUPPORTED_ENCODING_ERR"          : "Hình thức mã hóa không xác định.",
    "ENCODE_FILE_FAILED_ERR"            : "{APP_NAME} không thể mã hóa Tập tin này.",
    "DECODE_FILE_FAILED_ERR"            : "{APP_NAME} không thể giải mã Tập tin này.",
    "UNSUPPORTED_UTF16_ENCODING_ERR"    : "{APP_NAME} hiện tại không hỗ trợ các văn bản được mã hóa UTF-16.",
    "FILE_EXISTS_ERR"                   : "Tập tin/Thư mục đã tồn tại.",
    "FILE"                              : "Tập tin",
    "FILE_TITLE"                        : "Tập tin",
    "DIRECTORY"                         : "Thư mục",
    "DIRECTORY_TITLE"                   : "Thư mục",
    "DIRECTORY_NAMES_LEDE"              : "Tên nhóm Thư mục",
    "FILENAMES_LEDE"                    : "Tên nhóm Tập tin",
    "FILENAME"                          : "Tên Tập tin",
    "DIRECTORY_NAME"                    : "Tên Thư mục",

    // Project error strings
    "ERROR_LOADING_PROJECT"             : "Lỗi không tải được Dự án.",
    "OPEN_DIALOG_ERROR"                 : "Có lỗi khi mở Hộp thoại Tập tin. (Lỗi {0})",
    "REQUEST_NATIVE_FILE_SYSTEM_ERROR"  : "Có lỗi khi mở Thư mục <span class='dialog-filename'>{0}</span>. (Lỗi {1})",
    "READ_DIRECTORY_ENTRIES_ERROR"      : "Có lỗi khi đọc nội dung Thư mục <span class='dialog-filename'>{0}</span>. (Lỗi {1})",

    // File open/save error string
    "ERROR_OPENING_FILE_TITLE"          : "Không mở được Tập tin.",
    "ERROR_OPENING_FILE"                : "Có lỗi khi mở Tập tin <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_OPENING_FILES"               : "Có lỗi khi mở những Tập tin sau:",
    "ERROR_RELOADING_FILE_TITLE"        : "Có lỗi khi tải lại những thay đổi từ Ổ Đĩa",
    "ERROR_RELOADING_FILE"              : "Có lỗi khi tải lại Tập tin <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_SAVING_FILE_TITLE"           : "Lỗi lưu Tập tin",
    "ERROR_SAVING_FILE"                 : "Có lỗi khi lưu Tập tin <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_RENAMING_FILE_TITLE"         : "Lỗi đổi tên {0}",
    "ERROR_RENAMING_FILE"               : "Có lỗi khi đổi tên Tập tin {2} <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_RENAMING_NOT_IN_PROJECT"     : "Rât tiếc, Tập tin/Thư mục này không nằm trong Dự án đang mở. Bạn chỉ có thể đổi tên Tập tin/Thư mục trong Dự án.",
    "ERROR_MOVING_FILE_TITLE"           : "Lỗi chuyển Tập tin {0}",
    "ERROR_MOVING_FILE"                 : "Có lỗi khi di chuyển Tập tin {2} <span class='dialog-filename'>{0}</span>. {1}",
    "ERROR_MOVING_NOT_IN_PROJECT"       : "Không thể di chuyển Tập tin/Thư mục này, vì không nằm trong Dự án hiện tại.",
    "ERROR_DELETING_FILE_TITLE"         : "Lỗi xóa {0}",
    "ERROR_DELETING_FILE"               : "Có lỗi khi xóa Tập tin {2} <span class='dialog-filename'>{0}</span>. {1}",
    "INVALID_FILENAME_TITLE"            : "Lỗi đặt tên {0}",
    "INVALID_FILENAME_MESSAGE"          : "{0} không thể đặt trung tên đã có trong hệ thống, kết thúc bằng dấu chấm (.) hoặc bằng các kí tự sau: <code class='emphasized'>{1}</code>",
    "ENTRY_WITH_SAME_NAME_EXISTS"       : "Tập tin/Thư mục <span class='dialog-filename'>{0}</span> đã tồn tại.",
    "ERROR_CREATING_FILE_TITLE"         : "Lỗi tạo Tập tin{0}",
    "ERROR_CREATING_FILE"               : "Có lỗi khi tạo Tập tin {0} <span class='dialog-filename'>{1}</span>. {2}",
    "ERROR_MIXED_DRAGDROP"              : "Không thể mở Thư mục này cùng lúc với các Tập tin khác.",

    // User key map error strings
    "ERROR_KEYMAP_TITLE"                : "Lỗi đọc phím tắt",
    "ERROR_KEYMAP_CORRUPT"              : "Tập phím không phải là Tập tin JSON hợp lệ. Tập tin này sẽ được mở để bạn sửa theo dạng đúng.",
    "ERROR_LOADING_KEYMAP"              : "Tập phím của bạn không theo mẫu UTF-8 nên không thể tải",
    "ERROR_RESTRICTED_COMMANDS"         : "Không thể dùng phím tắt cho những mệnh lệnh này: {0}",
    "ERROR_RESTRICTED_SHORTCUTS"        : "Không thể thay đổi những phím tắt này: {0}",
    "ERROR_MULTIPLE_SHORTCUTS"          : "Bạn đang đặt nhiều phím tắt cho mệnh lệnh này: {0}",
    "ERROR_DUPLICATE_SHORTCUTS"         : "Các mệnh lệnh này đang có chung phím tắt: {0}",
    "ERROR_INVALID_SHORTCUTS"           : "Phím tắt không hợp lệ: {0}",
    "ERROR_NONEXISTENT_COMMANDS"        : "Bạn đang đặt phím tắt cho mệnh lệnh không tồn tại: {0}",

    // Application preferences corrupt error strings
    "ERROR_PREFS_CORRUPT_TITLE"         : "Lỗi đọc Cài đặt",
    "ERROR_PREFS_CORRUPT"               : "Tập tin Cài đặt không phải là Tập tin JSON hợp lệ. Tập tin này sẽ được mở để bạn sửa theo dạng đúng. Bạn sẽ phải khởi động lại {APP_NAME} để lưu các thay đổi.",
    "ERROR_PROJ_PREFS_CORRUPT"          : "Tập tin Cài đặt của dự án không phải là Tập JSON hợp lệ. Tập tin này sẽ được mở để bạn sửa theo dạng đúng. Bạn sẽ phải khởi động lại dự án để lưu các thay đổi.",

    // Application error strings
    "ERROR_IN_BROWSER_TITLE"            : "Xin lỗi! {APP_NAME} này vẫn chưa chạy được trên trình duyệt web.",
    "ERROR_IN_BROWSER"                  : "{APP_NAME} được viết bằng HTML, nhưng hiện tại vẫn là Ứng dụng desktop để bạn có thể chỉnh sửa Tập tin ở cục bộ. Xin hãy chạy {APP_NAME} bằng vỏ ứng dụng ở <b>github.com/adobe/brackets-shell</b>.",

    // ProjectManager max files error string
    "ERROR_MAX_FILES_TITLE"             : "Lỗi quá tải",
    "ERROR_MAX_FILES"                   : "Dự án này đã có hơn 30,000 Tập tin. Nhiều chức năng có thể bị vô hiệu hóa hoặc hoạt động như Dự án trống. <a href='https://github.com/adobe/brackets/wiki/Large-Projects'>Đọc thêm ở đây để biết thêm về cách xử lý Dự án lớn</a>.",

    // Live Preview error strings
    "ERROR_LAUNCHING_BROWSER_TITLE"     : "Lỗi mở trình duyệt Web",
    "ERROR_CANT_FIND_CHROME"            : "Không tìm thấy trình duyệt Google Chrome. Xin hãy cài đặt.",
    "ERROR_LAUNCHING_BROWSER"           : "Có lỗi khi mở trình duyệt Web. (error {0})",

    "LIVE_DEVELOPMENT_ERROR_TITLE"      : "Lỗi Giao diện Trực tiếp",
    "LIVE_DEVELOPMENT_RELAUNCH_TITLE"   : "Mở trình duyệt Web",
    "LIVE_DEVELOPMENT_ERROR_MESSAGE"    : "Chrome cần được khởi động lại với hệ thống debug để kết nối với Giao diện Trực tiếp.<br /><br />Xin hãy bật debug và khởi động lại Chrome.<br /><br />",
    "LIVE_DEV_LOADING_ERROR_MESSAGE"    : "Không tải được trang Bắt Đầu.",
    "LIVE_DEV_NEED_HTML_MESSAGE"        : "Hãy mở Tập tin HTML hoặc tạo Tập tin index.html trong Dự án để làm trang đầu cho Giao diện Trực Tiếp.",
    "LIVE_DEV_NEED_BASEURL_MESSAGE"     : "Nếu muốn mở Giao diện Trực tiếp với Tập tin phía máy chủ (server-side, PHP), cần phải chỉ nguồn URL cho dự án",
    "LIVE_DEV_SERVER_NOT_READY_MESSAGE" : "Có lỗi khi mở nguồn HTTP phía máy chủ cho Giao diện Trực tiếp. Xin hãy thử lại.",
    "LIVE_DEVELOPMENT_INFO_TITLE"       : "Chào mừng đến với Giao diện Trực tiếp!",
    "LIVE_DEVELOPMENT_INFO_MESSAGE"     : "Giao diện Trực tiếp sẽ kết nối {APP_NAME} đến trình duyệt web của bạn. Giao diện của Tập tin HTML sẽ hiện thị trên Chrome, và sẽ tự chỉnh sửa tức thì khi bạn thay đổi Tập tin HTML.<br /><br />In this early version of {APP_NAME}, Live Preview only works with <strong>Google Chrome</strong> and updates live as you edit <strong>CSS or HTML files</strong>. Changes to JavaScript files are automatically reloaded when you save.<br /><br />(You'll only see this message once.)",
    "LIVE_DEVELOPMENT_TROUBLESHOOTING"  : "Truy cập <a href='{0}' title='{0}'>Troubleshooting Live Preview connection errors</a>. để biết thêm thông tin",

    "LIVE_DEV_STATUS_TIP_NOT_CONNECTED" : "Giao diện Trực tiếp",
    "LIVE_DEV_STATUS_TIP_PROGRESS1"     : "Giao diện Trực tiếp: Đang kết nối\u2026",
    "LIVE_DEV_STATUS_TIP_PROGRESS2"     : "Giao diện Trực tiếp: Khởi động\u2026",
    "LIVE_DEV_STATUS_TIP_CONNECTED"     : "Hủy Giao diện Trực tiếp",
    "LIVE_DEV_STATUS_TIP_OUT_OF_SYNC"   : "Giao diện Trực tiếp (lưu Tập tin để khởi động lại)",
    "LIVE_DEV_STATUS_TIP_SYNC_ERROR"    : "Giao diện Trực tiếp (không cập nhật do lỗi cú pháp)",

    "LIVE_DEV_DETACHED_REPLACED_WITH_DEVTOOLS" : "Giao diện Trực tiếp bị hủy bởi công cụ lập trình của trình duyệt đang mở",
    "LIVE_DEV_DETACHED_TARGET_CLOSED"          : "Giao diện Trực tiếp bị hủy because trang giao diện (Tab) bị đóng",
    "LIVE_DEV_NAVIGATED_AWAY"                  : "Giao diện Trực tiếp bị hủy bởi trình duyệt đang mở trang khác ngoài Dự án",
    "LIVE_DEV_CLOSED_UNKNOWN_REASON"           : "Giao diện Trực tiếp bị hủy không rõ lý do ({0})",

    "SAVE_CLOSE_TITLE"                  : "Lưu thay đổi",
    "SAVE_CLOSE_MESSAGE"                : "Bạn có muốn lưu thay đổi với Tập tin này không? <span class='dialog-filename'>{0}</span>?",
    "SAVE_CLOSE_MULTI_MESSAGE"          : "Bạn có muốn lưu thay đổi với tất cả Tập tin này không?",
    "EXT_MODIFIED_TITLE"                : "Thay đổi bên ngoài",
    "CONFIRM_DELETE_TITLE"              : "Xác nhận xóa",
    "CONFIRM_FILE_DELETE"               : "Bạn có chắc là muốn xóa Tập tin này? <span class='dialog-filename'>{0}</span>?",
    "CONFIRM_FOLDER_DELETE"             : "Bạn có chắc là muốn xóa Thư mục này? <span class='dialog-filename'>{0}</span>?",
    "FILE_DELETED_TITLE"                : "Đã xóa",
    "EXT_MODIFIED_WARNING"              : "<span class='dialog-filename'>{0}</span> đã bị thay đổi ở ổ đĩa bên ngoài {APP_NAME}.<br /><br />Bạn có muốn lưu Tập tin và ghi đè những thay đổi này?",
    "EXT_MODIFIED_MESSAGE"              : "<span class='dialog-filename'>{0}</span> đã bị thay đổi ở ổ đĩa bên ngoài {APP_NAME}, nhưng {APP_NAME} cũng có những thay đổi chưa được lưu.<br /><br />Bạn muốn lưu bản nào?",
    "EXT_DELETED_MESSAGE"               : "<span class='dialog-filename'>{0}</span> đã bị xóa ở ổ đĩa bên ngoài {APP_NAME}, nhưng {APP_NAME} cũng có những thay đổi chưa được lưu.<br /><br />Bạn có muốn lưu thay đổi này?",
    
    // Window unload warning messages
    "WINDOW_UNLOAD_WARNING"                      : "Bạn có chắc là muốn đến URL khác và thoát khỏi Brackets?",
    "WINDOW_UNLOAD_WARNING_WITH_UNSAVED_CHANGES" : "Bạn chưa lưu thay đổi! Bạn có chắc là muốn đến URL khác và thoát khỏi Brackets?",

    // Generic dialog/button labels
    "DONE"                              : "Xong",
    "OK"                                : "OK",
    "CANCEL"                            : "Hủy",
    "DONT_SAVE"                         : "Không lưu",
    "SAVE"                              : "Lưu",
    "SAVE_AS"                           : "Lưu tên\u2026",
    "SAVE_AND_OVERWRITE"                : "Viết đè",
    "DELETE"                            : "Xóa",
    "BUTTON_YES"                        : "Có",
    "BUTTON_NO"                         : "Không",

    // Find, Replace, Find in Files
    "FIND_MATCH_INDEX"                  : "{0} của {1}",
    "FIND_NO_RESULTS"                   : "Không tìm thấy",
    "FIND_QUERY_PLACEHOLDER"            : "Tìm\u2026",
    "FIND_HISTORY_MAX_COUNT"            : "Số lượng kết quả tìm kiếm tối đa trong Lịch sử",
    "REPLACE_PLACEHOLDER"               : "Thay với\u2026",
    "BUTTON_REPLACE_ALL"                : "Thay tất cả",
    "BUTTON_REPLACE_BATCH"              : "Thay hàng loạt\u2026",
    "BUTTON_REPLACE_ALL_IN_FILES"       : "Thay\u2026",
    "BUTTON_REPLACE"                    : "Thay",
    "BUTTON_NEXT"                       : "\u25B6",
    "BUTTON_PREV"                       : "\u25C0",
    "BUTTON_NEXT_HINT"                  : "Tiếp theo",
    "BUTTON_PREV_HINT"                  : "Quay lại",
    "BUTTON_CASESENSITIVE_HINT"         : "Viết hoa",
    "BUTTON_REGEXP_HINT"                : "Câu/Từ cần tìm",
    "REPLACE_WITHOUT_UNDO_WARNING_TITLE": "Thay thế không hoàn tác",
    "REPLACE_WITHOUT_UNDO_WARNING"      : "{APP_NAME} sẽ thay đổi những Tập tin không mở trong ổ đĩa, vì có nhiều hơn {0} Tập tin cần được thay đổi.<br />Bạn sẽ không thể hoàn tác những thay đổi đó.",
    "BUTTON_REPLACE_WITHOUT_UNDO"       : "Thay thế không hoàn tác",

    "OPEN_FILE"                         : "Mở Tập tin",
    "SAVE_FILE_AS"                      : "Lưu Tập tin",
    "CHOOSE_FOLDER"                     : "Chọn Thư mục",

    "RELEASE_NOTES"                     : "Xuất bản Ghi chú",
    "NO_UPDATE_TITLE"                   : "Cập nhật!",
    "NO_UPDATE_MESSAGE"                 : "Bạn đang chạy {APP_NAME} bản mới nhất.",

    // Find and Replace
    "FIND_REPLACE_TITLE_LABEL"          : "Thay thế",
    "FIND_REPLACE_TITLE_WITH"           : "bằng",
    "FIND_TITLE_LABEL"                  : "Tìm kiếm",
    "FIND_TITLE_SUMMARY"                : "&mdash; {0} {1} {2} in {3}",

    // Find in Files
    "FIND_NUM_FILES"                    : "{0} {1}",
    "FIND_IN_FILES_SCOPED"              : "ở <span class='dialog-filename'>{0}</span>",
    "FIND_IN_FILES_NO_SCOPE"            : "trong dự án",
    "FIND_IN_FILES_ZERO_FILES"          : "Không bao gồm các Tập tin sau {0}",
    "FIND_IN_FILES_FILE"                : "Tập tin",
    "FIND_IN_FILES_FILES"               : "các Tập tin",
    "FIND_IN_FILES_MATCH"               : "trùng khớp",
    "FIND_IN_FILES_MATCHES"             : "trùng khớp",
    "FIND_IN_FILES_MORE_THAN"           : "Nhiều hơn ",
    "FIND_IN_FILES_PAGING"              : "{0}&mdash;{1}",
    "FIND_IN_FILES_FILE_PATH"           : "<span class='dialog-filename'>{0}</span> {2} <span class='dialog-path'>{1}</span>", // We should use normal dashes on Windows instead of em dash eventually
    "FIND_IN_FILES_EXPAND_COLLAPSE"     : "Bấm Ctrl/Cmd để Mở rộng/Thu gọn tất cả",
    "FIND_IN_FILES_INDEXING"            : "Tìm qua số dòng\u2026",
    "REPLACE_IN_FILES_ERRORS_TITLE"     : "Lỗi Thay thế",
    "REPLACE_IN_FILES_ERRORS"           : "Các Tập tin này không thể thay đổi vì chúng đã bị thay đổi sau cuộc tìm kiếm hoặc chỉ là không thể viết được.",

    "ERROR_FETCHING_UPDATE_INFO_TITLE"  : "Lỗi sửa đổi nội dung",
    "ERROR_FETCHING_UPDATE_INFO_MSG"    : "Có vấn đề khi kết nối thông tin với máy chủ. Xin hãy bảo đảm rằng kết nối Internet của bạn ổn định.",

    // File exclusion filters
    "NEW_FILE_FILTER"                   : "Không bao gồm các Tập tin\u2026",
    "CLEAR_FILE_FILTER"                 : "Không loại trừ các Tập tin này",
    "NO_FILE_FILTER"                    : "Không loại trừ Tập tin nào",
    "EXCLUDE_FILE_FILTER"               : "Loại trừ {0}",
    "EDIT_FILE_FILTER"                  : "Sửa đổi\u2026",
    "FILE_FILTER_DIALOG"                : "Thay đổi danh sách loại trừ",
    "FILE_FILTER_INSTRUCTIONS"          : "Loại trừ các Tập tin chứa câu/từ sau đây / substrings or <a href='{0}' title='{0}'>wildcards</a>. Hãy ghi câu/từ sau vào dong mới.",
    "FILTER_NAME_PLACEHOLDER"           : "Đặt tên danh sách loại trừ (tùy chọn)",
    "FILTER_NAME_REMAINING"             : "còn {0} chữ",
    "FILE_FILTER_CLIPPED_SUFFIX"        : "và {0} nữa",
    "FILTER_COUNTING_FILES"             : "Số lượng Tập tin\u2026",
    "FILTER_FILE_COUNT"                 : "Cho phép {0} của {1} Tập tin {2}",
    "FILTER_FILE_COUNT_ALL"             : "Cho phép tất cả {0} Tập tin {1}",

    // Quick Edit
    "ERROR_QUICK_EDIT_PROVIDER_NOT_FOUND"   : "Lựa chọn Sửa đổi không tồn tại cho vị trí con trỏ hiện tại",
    "ERROR_CSSQUICKEDIT_BETWEENCLASSES"     : "Lỗi viết CSS: đặt con trỏ vào tên class",
    "ERROR_CSSQUICKEDIT_CLASSNOTFOUND"      : "Lỗi viết CSS: không tìm thấy class",
    "ERROR_CSSQUICKEDIT_IDNOTFOUND"         : "Lỗi viết CSS: không tìm thấy id",
    "ERROR_CSSQUICKEDIT_UNSUPPORTEDATTR"    : "Lỗi viết CSS: hãy đựt con trot vào tag, class, hoặc id",
    "ERROR_TIMINGQUICKEDIT_INVALIDSYNTAX"   : "Lỗi thời gian viết CSS: cú pháp không hợp lệ",
    "ERROR_JSQUICKEDIT_FUNCTIONNOTFOUND"    : "Lỗi viết JS: đặt con trỏ vào tên function",

    // Quick Docs
    "ERROR_QUICK_DOCS_PROVIDER_NOT_FOUND"   : "Không có Tài liệu cho vị trí con trỏ hiện tại",

    /**
     * ProjectManager
     */
    "PROJECT_LOADING"   : "Đang tải\u2026",
    "UNTITLED"          : "Không tên",
    "WORKING_FILES"     : "Tập tin đang hiển thị",

    /**
     * MainViewManager
     */
    "TOP"               : "Lên đỉnh",
    "BOTTOM"            : "Xuống đáy",
    "LEFT"              : "Trái",
    "RIGHT"             : "Phỉa",

    "CMD_SPLITVIEW_NONE"        : "Không chia màn hình",
    "CMD_SPLITVIEW_VERTICAL"    : "Chia màn hình theo chiều dọc",
    "CMD_SPLITVIEW_HORIZONTAL"  : "Chia màn hình theo chiều ngang",
    "SPLITVIEW_MENU_TOOLTIP"    : "Chia màn hình theo chiều ngang hoặc chiều dọc",
    "GEAR_MENU_TOOLTIP"         : "Cài đặt máy tính",

    "SPLITVIEW_INFO_TITLE"              : "Đã mở",
    "SPLITVIEW_MULTIPANE_WARNING"       : "Tập tin đã mở ở khung hiển thị kia. {APP_NAME} sẽ sớm hỗ trợ mở một Tập tin trong nhiều khung. Nhưng hiện tại, Tập tin sẽ chỉ được mở trong khung này.<br /><br />(Bạn sẽ chỉ thấy thông báo này một lần.)",

    /**
     * Keyboard modifiers and special key names
     */
    "KEYBOARD_CTRL"         : "Ctrl",
    "KEYBOARD_SHIFT"        : "Shift",
    "KEYBOARD_SPACE"        : "Phím cách",
    "KEYBOARD_PAGE_UP"      : "Page Up",
    "KEYBOARD_PAGE_DOWN"    : "Page Down",
    "KEYBOARD_HOME"         : "Home",
    "KEYBOARD_END"          : "End",
    "KEYBOARD_INSERT"       : "Insert",
    "KEYBOARD_DELETE"       : "Delete",

    /**
     * StatusBar strings
     */
    "STATUSBAR_CURSOR_POSITION"             : "Dòng {0}, Cột {1}",
    "STATUSBAR_SELECTION_CH_SINGULAR"       : " \u2014 Chọn cột số {0}",
    "STATUSBAR_SELECTION_CH_PLURAL"         : " \u2014 Chọn những cột sau {0}",
    "STATUSBAR_SELECTION_LINE_SINGULAR"     : " \u2014 Chọn dòng số {0}",
    "STATUSBAR_SELECTION_LINE_PLURAL"       : " \u2014 Chọn những dòng sau {0}",
    "STATUSBAR_SELECTION_MULTIPLE"          : " \u2014 {0} lựa chọn",
    "STATUSBAR_INDENT_TOOLTIP_SPACES"       : "Chuyển cách dòng đầu sang dấu cách",
    "STATUSBAR_INDENT_TOOLTIP_TABS"         : "Chuyển cách dòng đầu sang dấu tab",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_SPACES"  : "Xác định số lần cách cho dòng đầu",
    "STATUSBAR_INDENT_SIZE_TOOLTIP_TABS"    : "Xác định chiều dài cho dấu tab",
    "STATUSBAR_SPACES"                      : "Số lần cách:",
    "STATUSBAR_TAB_SIZE"                    : "Cỡ tab:",
    "STATUSBAR_LINE_COUNT_SINGULAR"         : "\u2014 Dòng {0}",
    "STATUSBAR_LINE_COUNT_PLURAL"           : "\u2014 Dòng {0}",
    "STATUSBAR_USER_EXTENSIONS_DISABLED"    : "Ngưng Mở rộng Ứng dụng",
    "STATUSBAR_INSERT"                      : "INS",
    "STATUSBAR_OVERWRITE"                   : "OVR",
    "STATUSBAR_INSOVR_TOOLTIP"              : "Bấm để chuyển đổi giữa Viết chèn (INS) và Viết đè (OVR)",
    "STATUSBAR_LANG_TOOLTIP"                : "Bấm để thay đổi loại Tập tin",
    "STATUSBAR_CODE_INSPECTION_TOOLTIP"     : "{0}. Bấm để bật thanh thông báo.",
    "STATUSBAR_DEFAULT_LANG"                : "(tự động)",
    "STATUSBAR_SET_DEFAULT_LANG"            : "Thiết lập tự dộng cho tập tin .{0}",
    "STATUSBAR_ENCODING_TOOLTIP"            : "Chọn mã hóa",

    // CodeInspection: errors/warnings
    "ERRORS_PANEL_TITLE_MULTIPLE"           : "{0} Vấn đề",
    "SINGLE_ERROR"                          : "1 {0} Vấn đề",
    "MULTIPLE_ERRORS"                       : "{1} {0} Những vấn đề",
    "NO_ERRORS"                             : "Không {0} có vấn đề nào - chúc mừng!",
    "NO_ERRORS_MULTIPLE_PROVIDER"           : "Không tìm thấy vấn đề nào - chúc mừng!",
    "LINT_DISABLED"                         : "Ngưng Linting (Thuật ngữ Linux)",
    "NO_LINT_AVAILABLE"                     : "Không có linter (Thuật ngữ Linux) cho {0}",
    "NOTHING_TO_LINT"                       : "Không có gì để lint (Thuật ngữ Linux)",
    "LINTER_TIMED_OUT"                      : "{0} đã chạy quá lâu khi chờ {1} ms",
    "LINTER_FAILED"                         : "{0} bị hủy vì lỗi: {1}",

    /**
     * Command Name Constants
     */

    // File menu commands
    "FILE_MENU"                           : "Tập tin",
    "CMD_FILE_NEW_UNTITLED"               : "Tập tin mới",
    "CMD_FILE_NEW"                        : "Tập tin mới",
    "CMD_FILE_NEW_FOLDER"                 : "Thư mục mới",
    "CMD_FILE_OPEN"                       : "Mở\u2026",
    "CMD_RECENT_FILES_OPEN"               : "Mở Tập tin gần đây\u2026",
    "CMD_ADD_TO_WORKING_SET"              : "Thêm vào danh sách cần làm",
    "CMD_OPEN_DROPPED_FILES"              : "Mở Tập tin đã tải",
    "CMD_OPEN_FOLDER"                     : "Mở Thư mục\u2026",
    "CMD_FILE_CLOSE"                      : "Đóng",
    "CMD_FILE_CLOSE_ALL"                  : "Đóng tất cả",
    "CMD_FILE_CLOSE_LIST"                 : "Đóng danh sách",
    "CMD_FILE_CLOSE_OTHERS"               : "Đóng Tập tin khác",
    "CMD_FILE_CLOSE_ABOVE"                : "Đóng Tập tin ở Trên",
    "CMD_FILE_CLOSE_BELOW"                : "Đóng Tập tin ở Dưới",
    "CMD_FILE_SAVE"                       : "Lưu",
    "CMD_FILE_SAVE_ALL"                   : "Lưu hết",
    "CMD_FILE_SAVE_AS"                    : "Lưu như\u2026",
    "CMD_LIVE_FILE_PREVIEW"               : "Giao diện Trực tiếp",
    "CMD_TOGGLE_LIVE_PREVIEW_MB_MODE"     : "Mở Giao diện Trực tiếp thử nghiệm",
    "CMD_RELOAD_LIVE_PREVIEW"             : "Cố mở Giao diện Trực tiếp",
    "CMD_PROJECT_SETTINGS"                : "Cài đặt Dự án\u2026",
    "CMD_FILE_RENAME"                     : "Đổi tên",
    "CMD_FILE_DELETE"                     : "Xóa",
    "CMD_INSTALL_EXTENSION"               : "Cài đặt Mở rộng Ứng dụng\u2026",
    "CMD_EXTENSION_MANAGER"               : "Quản lý Mở rộng Ứng dụng\u2026",
    "CMD_FILE_REFRESH"                    : "Tải lại",
    "CMD_QUIT"                            : "Bỏ",
    // Used in native File menu on Windows
    "CMD_EXIT"                            : "Thoát",

    // Edit menu commands
    "EDIT_MENU"                           : "Sửa đổi",
    "CMD_UNDO"                            : "Hoàn tác",
    "CMD_REDO"                            : "Làm lại",
    "CMD_CUT"                             : "Cut",
    "CMD_COPY"                            : "Copy",
    "CMD_PASTE"                           : "Paste",
    "CMD_SELECT_ALL"                      : "Chọn tất",
    "CMD_SELECT_LINE"                     : "Chọn dòng",
    "CMD_SPLIT_SEL_INTO_LINES"            : "Chia Lựa chọn thành từng dòng",
    "CMD_ADD_CUR_TO_NEXT_LINE"            : "Thêm con trỏ vào dòng tiếp theo",
    "CMD_ADD_CUR_TO_PREV_LINE"            : "Thêm con trỏ vào dòng trước",
    "CMD_INDENT"                          : "Cách lề",
    "CMD_UNINDENT"                        : "Hủy cách lề",
    "CMD_DUPLICATE"                       : "Sao chép",
    "CMD_DELETE_LINES"                    : "Xóa dòng",
    "CMD_COMMENT"                         : "Tạo Bình luận dòng",
    "CMD_BLOCK_COMMENT"                   : "Tạo Bình luận khối",
    "CMD_LINE_UP"                         : "Lên dòng trên",
    "CMD_LINE_DOWN"                       : "Xuống dòng dưới",
    "CMD_OPEN_LINE_ABOVE"                 : "Tạo dòng trên",
    "CMD_OPEN_LINE_BELOW"                 : "Tạo dòng dưới",
    "CMD_TOGGLE_CLOSE_BRACKETS"           : "Tự động đóng ngoặc",
    "CMD_SHOW_CODE_HINTS"                 : "Gợi ý viết mã",

    // Search menu commands
    "FIND_MENU"                           : "Tìm kiếm",
    "CMD_FIND"                            : "Tìm kiếm",
    "CMD_FIND_NEXT"                       : "Kết quả Tiếp",
    "CMD_FIND_PREVIOUS"                   : "Kết quả Trước",
    "CMD_FIND_ALL_AND_SELECT"             : "Tất cả kết quả",
    "CMD_ADD_NEXT_MATCH"                  : "Thêm Kết quả tiếp theo vào Danh sách",
    "CMD_SKIP_CURRENT_MATCH"              : "Bỏ qua rồi thêm Kết quả tiếp theo",
    "CMD_FIND_IN_FILES"                   : "Tìm kiếm ở tất cả Tập tin",
    "CMD_FIND_IN_SUBTREE"                 : "Tìm kiếm ở\u2026",
    "CMD_REPLACE"                         : "Thay thế",
    "CMD_REPLACE_IN_FILES"                : "Thay thế ở tất cả Tập tin",
    "CMD_REPLACE_IN_SUBTREE"              : "Thay thế ở\u2026",

    // View menu commands
    "VIEW_MENU"                           : "Hiển thị",
    "CMD_HIDE_SIDEBAR"                    : "Ẩn Thanh công cụ",
    "CMD_SHOW_SIDEBAR"                    : "Hiện Thanh công cụ",
    "CMD_TOGGLE_SIDEBAR"                  : "Hiện/Ẩn Thanh công cụ",
    "CMD_TOGGLE_PANELS"                   : "Hiện/Ẩn khung hình",
    "CMD_TOGGLE_PURE_CODE"                : "Ẩn danh sách Tập tin",
    "CMD_INCREASE_FONT_SIZE"              : "Tăng cỡ chữ",
    "CMD_DECREASE_FONT_SIZE"              : "Giảm cỡ chữ",
    "CMD_RESTORE_FONT_SIZE"               : "Khôi phục cỡ chữ",
    "CMD_SCROLL_LINE_UP"                  : "Chuyển lên một dòng",
    "CMD_SCROLL_LINE_DOWN"                : "Chuyển xuống một dòng",
    "CMD_TOGGLE_LINE_NUMBERS"             : "Số dòng",
    "CMD_TOGGLE_ACTIVE_LINE"              : "Tô đậm dòng hiện tại",
    "CMD_TOGGLE_WORD_WRAP"                : "Gói từ",
    "CMD_LIVE_HIGHLIGHT"                  : "Điểm nhấn Giao diện Trực tiếp",
    "CMD_VIEW_TOGGLE_INSPECTION"          : "Tập tin Lint khi lưu",
    "CMD_WORKINGSET_SORT_BY_ADDED"        : "Sắp xếp theo Ngày thêm",
    "CMD_WORKINGSET_SORT_BY_NAME"         : "Sắp xếp theo Tên",
    "CMD_WORKINGSET_SORT_BY_TYPE"         : "Sắp xếp theo Loại",
    "CMD_WORKING_SORT_TOGGLE_AUTO"        : "Tự động Sắp xếp",
    "CMD_THEMES"                          : "Trang trí\u2026",
    "CMD_TOGGLE_SEARCH_AUTOHIDE"          : "Tự động đóng Tìm kiếm",

    // Navigate menu commands
    "NAVIGATE_MENU"                       : "Định vị",
    "CMD_QUICK_OPEN"                      : "Mở Tập tin",
    "CMD_GOTO_LINE"                       : "Đến dòng",
    "CMD_GOTO_DEFINITION"                 : "Định vị bằng Từ khóa",
    "CMD_GOTO_DEFINITION_PROJECT"         : "Định vị bằng Từ khóa của Dự án",
    "CMD_GOTO_FIRST_PROBLEM"              : "Đến lỗi đầu tiên",
    "CMD_TOGGLE_QUICK_EDIT"               : "Định vị Chỉnh sửa",
    "CMD_TOGGLE_QUICK_DOCS"               : "Định vị Tài liệu",
    "CMD_QUICK_EDIT_PREV_MATCH"           : "Kết quả trước",
    "CMD_QUICK_EDIT_NEXT_MATCH"           : "Kết quả tiếp",
    "CMD_CSS_QUICK_EDIT_NEW_RULE"         : "Tạo luật",
    "CMD_NEXT_DOC"                        : "Tài liệu tiếp",
    "CMD_PREV_DOC"                        : "Tài liệu trước",
    "CMD_NAVIGATE_BACKWARD"               : "Định vị ngược chiều",
    "CMD_NAVIGATE_FORWARD"                : "Định vị xuôi chiều",
    "CMD_NEXT_DOC_LIST_ORDER"             : "Tài liệu tiếp trong Danh sách",
    "CMD_PREV_DOC_LIST_ORDER"             : "Tài liệu trước trong Danh sách",
    "CMD_SHOW_IN_TREE"                    : "Hiển thị trên Sơ đồ cây",
    "CMD_SHOW_IN_EXPLORER"                : "Hiển thị trên Explorer",
    "CMD_SHOW_IN_FINDER"                  : "Hiển thị trên Finder",
    "CMD_SHOW_IN_OS"                      : "Hiển thị trên OS",
    "CMD_SWITCH_PANE_FOCUS"               : "Chuyển trọng tâm",

    // Help menu commands
    "HELP_MENU"                           : "Trợ giúp",
    "CMD_CHECK_FOR_UPDATE"                : "Thông báo Cập nhật",
    "CMD_HOW_TO_USE_BRACKETS"             : "Cách dùng {APP_NAME}",
    "CMD_SUPPORT"                         : "Hỗ trợ {APP_NAME}",
    "CMD_SUGGEST"                         : "Gợi ý",
    "CMD_RELEASE_NOTES"                   : "Ghi chú",
    "CMD_GET_INVOLVED"                    : "Cách Đóng góp",
    "CMD_SHOW_EXTENSIONS_FOLDER"          : "Hiển thị thư mục Ứng dụng Mở rộng",
    "CMD_HEALTH_DATA_STATISTICS"          : "Báo cáo tình trạng",
    "CMD_HOMEPAGE"                        : "Trang chủ {APP_TITLE}",
    "CMD_TWITTER"                         : "{TWITTER_NAME} trên Twitter",
    "CMD_ABOUT"                           : "Thông tin về {APP_TITLE}",
    "CMD_OPEN_PREFERENCES"                : "Mở Tập tin Sở thích",
    "CMD_OPEN_KEYMAP"                     : "Mở bàn phím",

    // Strings for main-view.html
    "EXPERIMENTAL_BUILD"                   : "lập trình thử nghiệm",
    "RELEASE_BUILD"                        : "lập trình",
    "DEVELOPMENT_BUILD"                    : "quá trình lập trình",
    "PRERELEASE_BUILD"                     : "bản phát hành trước",
    "RELOAD_FROM_DISK"                     : "Tải lại từ Ổ đĩa",
    "KEEP_CHANGES_IN_EDITOR"               : "Lưu Thay đổi",
    "CLOSE_DONT_SAVE"                      : "Đóng (Không lưu)",
    "RELAUNCH_CHROME"                      : "Tải lại Chrome",
    "ABOUT"                                : "Thông tin",
    "CLOSE"                                : "Đóng",
    "ABOUT_TEXT_LINE1"                     : "Bản {VERSION_MAJOR}.{VERSION_MINOR} {BUILD_TYPE} {VERSION}",
    "ABOUT_TEXT_BUILD_TIMESTAMP"           : "Thời gian: ",
    "ABOUT_TEXT_LINE3"                     : "Thông báo, điều khoản và điều kiện liên quan đến phần mềm của bên thứ ba được đặt tại <a href='{ADOBE_THIRD_PARTY}'>{ADOBE_THIRD_PARTY}</a> và được liên kết bởi tài liệu tham khảo này.",
    "ABOUT_TEXT_LINE4"                     : "Tài liệu và nguồn ở <a href='https://github.com/adobe/brackets/'>https://github.com/adobe/brackets/</a>",
    "ABOUT_TEXT_LINE5"                     : "Tạo bởi \u2764 và JavaScript:",
    "ABOUT_TEXT_LINE6"                     : "Rất nhiều người (nhưng chúng tôi đang cố gắng tải dữ liệu).",
    "ABOUT_TEXT_MDN_DOCS"                  : "Bản quyền của MDN Docs và MDN graphical logo ở 'Creative Commons Attribution license', <a href='{MDN_DOCS_LICENSE}'>CC-BY-SA 2.5 Unported</a>.",
    "UPDATE_NOTIFICATION_TOOLTIP"          : "Có phiên bản mới của {APP_NAME}! Bấm để biết thêm chi tiết.",
    "UPDATE_AVAILABLE_TITLE"               : "Thông báo Cập nhật",
    "UPDATE_MESSAGE"                       : "Ê, có phiên bản mới của {APP_NAME}. Đây là những chi tiết mới:",
    "GET_IT_NOW"                           : "Tải đê nào!",
    "PROJECT_SETTINGS_TITLE"               : "Cài đặt cho Dự án: {0}",
    "PROJECT_SETTING_BASE_URL"             : "URL chính của Giao diện Trực tiếp",
    "PROJECT_SETTING_BASE_URL_HINT"        : "Nếu muốn dùng máy chủ của bạn, hãy dùng URL như http://localhost:8000/",
    "BASEURL_ERROR_INVALID_PROTOCOL"       : "Giao thức {0} không được hỗ trợ bởi Giao diện Trực tiếp &mdash;please use http: or https: .",
    "BASEURL_ERROR_SEARCH_DISALLOWED"      : "URL không thể chứa các ký tự như \"{0}\".",
    "BASEURL_ERROR_HASH_DISALLOWED"        : "URL không thể chứa các cụm từ tìm kiếm như \"{0}\".",
    "BASEURL_ERROR_INVALID_CHAR"           : "Ký tự đặc biệt như '{0}' phải được mã hóa %.",
    "BASEURL_ERROR_UNKNOWN_ERROR"          : "Lỗi không xác định khi xử lý URL",

    // Strings for Pane.js
    "EMPTY_VIEW_HEADER"                    : "<em>Mở tập tin khi khung hình còn trống</em>",
    "FLIPVIEW_BTN_TOOLTIP"                 : "Chuyển giao diện sang khung {0}",

    // Strings for themes-settings.html and themes-general.html
    "CURRENT_THEME"                        : "Cài đặt hiện tại",
    "USE_THEME_SCROLLBARS"                 : "Dùng Thanh công cụ cho Cài đặt",
    "FONT_SIZE"                            : "Cỡ chữ",
    "FONT_FAMILY"                          : "Kiểm chữ",
    "THEMES_SETTINGS"                      : "Cài đặt",

    // Lỗi viết CSS
    "BUTTON_NEW_RULE"                      : "Tạo Luật",

    // Extension Management strings
    "INSTALL"                              : "Tải về",
    "UPDATE"                               : "Cập nhật",
    "REMOVE"                               : "Gỡ bỏ",
    "DISABLE"                              : "Vô hiệu",
    "ENABLE"                               : "Cho phép",
    "OVERWRITE"                            : "Ghi đè",
    "CANT_REMOVE_DEV"                      : "Ứng dụng trong Thư mục \"dev\" chỉ có thể xóa trực tiếp.",
    "CANT_UPDATE"                          : "Phiên bản mới không tương thích với {APP_NAME}.",
    "CANT_UPDATE_DEV"                      : "Ứng dụng trong Thư mục \"dev\" không thể tự động cập nhật.",
    "INSTALL_EXTENSION_TITLE"              : "Tải Ứng dụng",
    "UPDATE_EXTENSION_TITLE"               : "Cập nhật Ứng dụng",
    "INSTALL_EXTENSION_LABEL"              : "URL của Ứng dụng",
    "INSTALL_EXTENSION_HINT"               : "URL của tập tin zip/trang GitHub của Ứng dụng",
    "INSTALLING_FROM"                      : "Tải Ứng dụng từ {0}\u2026",
    "INSTALL_SUCCEEDED"                    : "Tải về thành công.",
    "INSTALL_FAILED"                       : "Tải về thất bại.",
    "CANCELING_INSTALL"                    : "Hủy\u2026",
    "CANCELING_HUNG"                       : "Hủy do quá lâu. Lỗi có thể đã xảy ra.",
    "INSTALL_CANCELED"                     : "Hủy Tải về.",
    "VIEW_COMPLETE_DESCRIPTION"            : "Mô tả đầy đủ",
    "VIEW_TRUNCATED_DESCRIPTION"           : "Mô tả vắn tắt",
    "SORT_EXTENSION_METHOD"                : "Sắp xếp Ứng dụng bằng downloadCount hoặc publishedDate",
    
    // These must match the error codes in ExtensionsDomain.Errors.* :
    "INVALID_ZIP_FILE"                     : "Tệp đã tải xuống không phải là tệp zip hợp lệ.",
    "MISSING_PACKAGE_JSON"                 : "Tệp package.json không tồn tại.",
    "INVALID_PACKAGE_JSON"                 : "Tệp package.json không hợp lệ (lỗi là: {0}).",
    "MISSING_PACKAGE_NAME"                 : "Tệp package.json không chứa tên package",
    "BAD_PACKAGE_NAME"                     : "{0} không phải tên hợp lên.",
    "MISSING_PACKAGE_VERSION"              : "Tệp package.json không chứa phiên bản package.",
    "INVALID_VERSION_NUMBER"               : "Số phiên bản package ({0}) không hợp lệ.",
    "INVALID_BRACKETS_VERSION"             : "Phiên bản {APP_NAME} ({0}) không hợp lệ.",
    "DISALLOWED_WORDS"                     : "Từ ({1}) không hợp lệ ở {0}.",
    "NPM_INSTALL_FAILED"                   : "Tải mã lệnh npm thất bại: {0}",
    "API_NOT_COMPATIBLE"                   : "Ứng dụng không tương thích với phiên bản này của {APP_NAME}. Nó đã được chuyển đến Tập tin disabled extensions.",
    "MISSING_MAIN"                         : "Tập tin main.js không tồn tại.",
    "EXTENSION_ALREADY_INSTALLED"          : "Tải Package này sẽ chèn lên phiên bản trước. Bạn có muốn vậy?",
    "EXTENSION_SAME_VERSION"               : "Package này cùng phiên bản với loại đã tải. Bạn có muốn viết đè lên bản cũ?",
    "EXTENSION_OLDER_VERSION"              : "Package là bản {0}, cũ hơn với loại đã tải là bản ({1}). Bạn có muốn viết đè lên bản cũ?",
    "DOWNLOAD_ID_IN_USE"                   : "Lỗi nội tại: ID này đã được sử dụng.",
    "NO_SERVER_RESPONSE"                   : "Không kết nối được với máy chủ.",
    "BAD_HTTP_STATUS"                      : "Không tìm được Tập tin ở máy chủ (HTTP {0}).",
    "CANNOT_WRITE_TEMP"                    : "Không tạo được Tập tin tạm thời.",
    "ERROR_LOADING"                        : "Ứng dụng bị lỗi khi mở.",
    "MALFORMED_URL"                        : "URL không hợp lệ. Xin hãy kiểm tra lại.",
    "UNSUPPORTED_PROTOCOL"                 : "URL phải chứa http hoặc https.",
    "UNKNOWN_ERROR"                        : "Lỗi không xác định.",

    // For NOT_FOUND_ERR, see generic strings above
    "EXTENSION_MANAGER_TITLE"              : "Quản lý Ứng dụng",
    "EXTENSION_MANAGER_ERROR_LOAD"         : "Không đăng nhập được vào kho Ứng dụng. Xin hãy thử lại lần sau.",
    "INSTALL_EXTENSION_DRAG"               : "Thả tệp .zip tại đây hoặc",
    "INSTALL_EXTENSION_DROP"               : "Thả tệp .zip để tải",
    "INSTALL_EXTENSION_DROP_ERROR"         : "Hủy bỏ Tải/Cập nhật vì lỗi sau:",
    "INSTALL_FROM_URL"                     : "Tải từ URL\u2026",
    "INSTALL_EXTENSION_VALIDATING"         : "Xác nhận\u2026",
    "EXTENSION_AUTHOR"                     : "Tác giả",
    "EXTENSION_DATE"                       : "Ngày",
    "EXTENSION_INCOMPATIBLE_NEWER"         : "Ứng dụng này chỉ hoạt động với bản mới của {APP_NAME}.",
    "EXTENSION_INCOMPATIBLE_OLDER"         : "Ứng dụng này chỉ hoạt động với bản cũ của  {APP_NAME}.",
    "EXTENSION_LATEST_INCOMPATIBLE_NEWER"  : "Phiên bản {0} của Ứng dụng này cần bản mới hơn của {APP_NAME}. Nhưng bạn có thể dùng bản này {1}.",
    "EXTENSION_LATEST_INCOMPATIBLE_OLDER"  : "Phiên bản {0} của Ứng dụng này cần bản cũ hơn của{APP_NAME}. Nhưng bạn có thể dùng bản này {1}.",
    "EXTENSION_NO_DESCRIPTION"             : "Không có Mô tả",
    "EXTENSION_MORE_INFO"                  : "Thông tin\u2026",
    "EXTENSION_ERROR"                      : "Lỗi Ứng dụng",
    "EXTENSION_KEYWORDS"                   : "Từ khóa",
    "EXTENSION_TRANSLATED_USER_LANG"       : "Dịch sang tiếng {0}, bao gồm ngôn ngữ của bạn",
    "EXTENSION_TRANSLATED_GENERAL"         : "Dịch sang tiếng {0}",
    "EXTENSION_TRANSLATED_LANGS"           : "Ứng dụng này đã được dịch sang ngôn ngữ sau: {0}",
    "EXTENSION_INSTALLED"                  : "Đã tải",
    "EXTENSION_UPDATE_INSTALLED"           : "Ứng dụng đã cập nhật và sẽ được tải sau khi {APP_NAME} khởi động lại.",
    "EXTENSION_SEARCH_PLACEHOLDER"         : "Tìm kiếm",
    "EXTENSION_MORE_INFO_LINK"             : "Thêm thông tin",
    "BROWSE_EXTENSIONS"                    : "Ứng dụng Duyệt trình",
    "EXTENSION_MANAGER_REMOVE"             : "Xóa Ứng dụng",
    "EXTENSION_MANAGER_REMOVE_ERROR"       : "Không thể xóa một hay nhiều ứng dụng: {0}. {APP_NAME} vẫn sẽ khởi động lại.",
    "EXTENSION_MANAGER_UPDATE"             : "Cập nhật Ứng dụng",
    "EXTENSION_MANAGER_UPDATE_ERROR"       : "Không thể cập nhật một hay nhiều ứng dụng: {0}. {APP_NAME} vẫn sẽ khởi động lại.",
    "EXTENSION_MANAGER_DISABLE"            : "Tắt Ứng dụng",
    "EXTENSION_MANAGER_DISABLE_ERROR"      : "Không thể tắt một hay nhiều ứng dụng: {0}. {APP_NAME} vẫn sẽ khởi động lại.",
    "MARKED_FOR_REMOVAL"                   : "Đánh dấu để xóa",
    "UNDO_REMOVE"                          : "Làm lại",
    "MARKED_FOR_UPDATE"                    : "Đánh dấu để Cập nhật",
    "UNDO_UPDATE"                          : "Làm lại",
    "MARKED_FOR_DISABLING"                 : "Đánh dấu để Vô hiệu",
    "UNDO_DISABLE"                         : "Làm lại",
    "CHANGE_AND_RELOAD_TITLE"              : "Thay đổi ứng dụng",
    "CHANGE_AND_RELOAD_MESSAGE"            : "{APP_NAME} cần khởi động lại để phần đánh dấu được Cập nhật, Xóa hoặc Vô hiệu. Bạn sẽ được thông báo về các thay đổi chưa lưu.",
    "REMOVE_AND_RELOAD"                    : "Xóa Ứng dụng và Khởi động lại",
    "CHANGE_AND_RELOAD"                    : "Thay đổi Ứng dụng và Khởi động lại",
    "UPDATE_AND_RELOAD"                    : "Cập nhật Ứng dụng và Khởi động lại",
    "DISABLE_AND_RELOAD"                   : "Tắt Ứng dụng và Khởi động lại",
    "PROCESSING_EXTENSIONS"                : "Tiếp tục thay đổi Ứng dụng\u2026",
    "EXTENSION_NOT_INSTALLED"              : "Không thể xóa Ứng dụng {0} vì nó chưa được tải.",
    "NO_EXTENSIONS"                        : "Chưa tải Ứng dụng nào.<br>Bấm vào thanh Tải về để bắt đầu.",
    "NO_EXTENSION_MATCHES"                 : "Không tìm thấy Ứng dụng cần tìm.",
    "REGISTRY_SANITY_CHECK_WARNING"        : "Lưu ý: Ứng dụng này có thể được viết bởi Tác giả khác ngoài của {APP_NAME}. Ứng dụng chưa được kiểm tra và có thể tùy ý ảnh hưởng máy chủ. Hãy lưu ý khi tải Ứng dụng lạ từ nguồn ngoài.",
    "EXTENSIONS_INSTALLED_TITLE"           : "Đã tải",
    "EXTENSIONS_DEFAULT_TITLE"             : "Mặc định",
    "EXTENSIONS_AVAILABLE_TITLE"           : "Tải về",
    "EXTENSIONS_THEMES_TITLE"              : "Cài đặt",
    "EXTENSIONS_UPDATES_TITLE"             : "Cập nhật",
    "EXTENSIONS_LAST_UPDATED"              : "Bản cập nhật trước",
    "EXTENSIONS_DOWNLOADS"                 : "Downloads",

    "INLINE_EDITOR_NO_MATCHES"             : "Không tìm thấy.",
    "INLINE_EDITOR_HIDDEN_MATCHES"         : "Tất cả kết quả đã bị đóng. Mở rộng danh sách tập tin bên phải để xem kết quả.",
    "CSS_QUICK_EDIT_NO_MATCHES"            : "Không tìm thấy luật CSS này.<br> Bấm \"Tạo luật\" để tạo luật mới.",
    "CSS_QUICK_EDIT_NO_STYLESHEETS"        : "Dự án không có tệp stylesheets.<br>Hãy tạo tệp rồi tạo luật CSS.",

    // Custom Viewers
    "IMAGE_VIEWER_LARGEST_ICON"            : "lớn nhất",

    /**
     * Unit names
     */
    "UNIT_PIXELS"                          : "pixels",

    // extensions/default/DebugCommands
    "DEBUG_MENU"                                : "Debug",
    "ERRORS"                                    : "Lỗi",
    "CMD_SHOW_DEV_TOOLS"                        : "Công cụ Lập trình",
    "CMD_REFRESH_WINDOW"                        : "Tải lại với Ứng dụng",
    "CMD_RELOAD_WITHOUT_USER_EXTS"              : "Tải lại không bao gồm Ứng dụng",
    "CMD_NEW_BRACKETS_WINDOW"                   : "Mở {APP_NAME} Window mới",
    "CMD_LAUNCH_SCRIPT_MAC"                     : "Tải Lối tắt",
    "CMD_SWITCH_LANGUAGE"                       : "Đổi ngôn ngữ",
    "CMD_RUN_UNIT_TESTS"                        : "Chạy Tests",
    "CMD_SHOW_PERF_DATA"                        : "Xem Chỉ số",
    "CMD_ENABLE_NODE_DEBUGGER"                  : "Mở Node Debugger",
    "CMD_LOG_NODE_STATE"                        : "Log Node State to Console",
    "CMD_RESTART_NODE"                          : "Khởi động lại Node",
    "CMD_SHOW_ERRORS_IN_STATUS_BAR"             : "Xem Errors ở Thanh Tình trạng",
    "CMD_OPEN_BRACKETS_SOURCE"                  : "Mở Nguồn {APP_NAME}",

    "CREATING_LAUNCH_SCRIPT_TITLE"              : "Lối tắt {APP_NAME}",
    "ERROR_CREATING_LAUNCH_SCRIPT"              : "Có lỗi khi tải lối tắt. Hãy thử <a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments#troubleshooting'> các gợi ý xử lý này</a>.<br/><br/>Lý do: {0}",
    "ERROR_CLTOOLS_RMFAILED"                    : "Không thể xóa symlink <code>/usr/local/bin/brackets</code>.",
    "ERROR_CLTOOLS_MKDIRFAILED"                 : "Không thể tạo Thư mục <code>/usr/local/bin</code>.",
    "ERROR_CLTOOLS_LNFAILED"                    : "Không thể tạo symlink <code>/usr/local/bin/brackets</code>.",
    "ERROR_CLTOOLS_SERVFAILED"                  : "Lỗi.",
    "ERROR_CLTOOLS_NOTSUPPORTED"                : "Bản OS này không hỗ trợ Lối tắt.",
    "LAUNCH_SCRIPT_CREATE_SUCCESS"              : "Thành công! Bạn đã có thể mở {APP_NAME} từ mệnh lệnh: <code>brackets myFile.txt</code> để mở tập tin hoặc <code>brackets myFolder</code> để đổi dự án. <br/><br/><a href='https://github.com/adobe/brackets/wiki/Command-Line-Arguments'>Biết thêm</a> về cách dùng {APP_NAME} bằng mệnh lệnh.",

    "LANGUAGE_TITLE"                            : "Đổi Ngôn ngữ",
    "LANGUAGE_MESSAGE"                          : "Ngôn ngữ:",
    "LANGUAGE_SUBMIT"                           : "Khởi động lại {APP_NAME}",
    "LANGUAGE_CANCEL"                           : "Hủy",
    "LANGUAGE_SYSTEM_DEFAULT"                   : "Mặc định",

    // extensions/default/HealthData
    "HEALTH_DATA_NOTIFICATION"                  : "Health Report Preferences",
    "HEALTH_FIRST_POPUP_TITLE"                  : "{APP_NAME} Health Report",
    "HEALTH_DATA_DO_TRACK"                      : "Share pseudonymous information on how I use {APP_NAME}",
    "HEALTH_DATA_NOTIFICATION_MESSAGE"          : "In order to improve {APP_NAME}, we periodically send limited, <strong>pseudonymous</strong> statistics to Adobe about how you use {APP_NAME}. This information helps prioritize features, find bugs, and spot usability issues.<br><br>You can see your data or choose not to share data by selecting <strong>Help > Health Report</strong>.<br><br><a href='https://github.com/adobe/brackets/wiki/Project-Health-Data'>Learn more about {APP_NAME} Health Report</a>",
    "HEALTH_DATA_PREVIEW"                       : "{APP_NAME} Health Report",
    "HEALTH_DATA_PREVIEW_INTRO"                 : "<p>In order to improve {APP_NAME}, we periodically send limited, <strong>pseudonymous</strong> statistics to Adobe about how you use {APP_NAME}. This information helps prioritize features, find bugs, and spot usability issues. <a href='https://github.com/adobe/brackets/wiki/Project-Health-Data'>Learn more about {APP_NAME} Health Report</a> and how it benefits the {APP_NAME} community while protecting your privacy.</p><p>Below is a preview of the data that will be sent in your next Health Report <em>if</em> it is enabled.</p>",

    // extensions/default/InlineTimingFunctionEditor
    "INLINE_TIMING_EDITOR_TIME"                 : "Time",
    "INLINE_TIMING_EDITOR_PROGRESSION"          : "Progression",
    "BEZIER_EDITOR_INFO"                        : "<kbd>↑</kbd><kbd>↓</kbd><kbd>←</kbd><kbd>→</kbd> Move selected point<br><kbd class='text'>Shift</kbd> Move by ten units<br><kbd class='text'>Tab</kbd> Switch points",
    "STEPS_EDITOR_INFO"                         : "<kbd>↑</kbd><kbd>↓</kbd> Increase or decrease steps<br><kbd>←</kbd><kbd>→</kbd> 'Start' or 'End'",
    "INLINE_TIMING_EDITOR_INVALID"              : "The old value <code>{0}</code> is not valid, so the displayed function was changed to <code>{1}</code>. The document will be updated with the first edit.",

    // extensions/default/InlineColorEditor
    "COLOR_EDITOR_CURRENT_COLOR_SWATCH_TIP"     : "Current Color",
    "COLOR_EDITOR_ORIGINAL_COLOR_SWATCH_TIP"    : "Original Color",
    "COLOR_EDITOR_RGBA_BUTTON_TIP"              : "RGBa Format",
    "COLOR_EDITOR_HEX_BUTTON_TIP"               : "Hex Format",
    "COLOR_EDITOR_HSLA_BUTTON_TIP"              : "HSLa Format",
    "COLOR_EDITOR_0X_BUTTON_TIP"                : "Hex (0x) Format",
    "COLOR_EDITOR_USED_COLOR_TIP_SINGULAR"      : "{0} (Used {1} time)",
    "COLOR_EDITOR_USED_COLOR_TIP_PLURAL"        : "{0} (Used {1} times)",

    // extensions/default/JavaScriptCodeHints
    "CMD_JUMPTO_DEFINITION"                     : "Jump to Definition",
    "CMD_SHOW_PARAMETER_HINT"                   : "Show Parameter Hint",
    "NO_ARGUMENTS"                              : "<no parameters>",
    "DETECTED_EXCLUSION_TITLE"                  : "JavaScript File Inference Problem",
    "DETECTED_EXCLUSION_INFO"                   : "{APP_NAME} ran into trouble processing <span class='dialog-filename'>{0}</span>.<br><br>This file will no longer be processed for code hints, Jump to Definition or Quick Edit. To re-enable this file, open <code>.brackets.json</code> in your project and edit <code>jscodehints.detectedExclusions</code>.<br><br>This is likely a {APP_NAME} bug. If you can provide a copy of this file, please <a href='https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue'>file a bug</a> with a link to the file named here.",

    // extensions/default/JavascriptRefactoring
    "CMD_REFACTOR"                              : "Refactor",
    "CMD_EXTRACTTO_VARIABLE"                    : "Extract to Variable",
    "CMD_EXTRACTTO_FUNCTION"                    : "Extract to Function",
    "ERROR_TERN_FAILED"                         : "Unable to get data from Tern",
    "ERROR_EXTRACTTO_VARIABLE_NOT_VALID"        : "Selection does not form an expression",
    "ERROR_EXTRACTTO_FUNCTION_NOT_VALID"        : "Selected block should represent set of statements or an expression",
    "ERROR_EXTRACTTO_VARIABLE_MULTICURSORS"     : "Extract to Variable does not work in multicursors",
    "ERROR_EXTRACTTO_FUNCTION_MULTICURSORS"     : "Extract to Function does not work in multicursors",
    "EXTRACTTO_FUNCTION_SELECT_SCOPE"           : "Choose destination scope",
    "EXTRACTTO_VARIABLE_SELECT_EXPRESSION"      : "Select an expression",
    "CMD_REFACTORING_RENAME"                    : "Rename",
    "CMD_REFACTORING_TRY_CATCH"                 : "Wrap in Try Catch",
    "CMD_REFACTORING_CONDITION"                 : "Wrap in Condition",
    "CMD_REFACTORING_GETTERS_SETTERS"           : "Create Getters/Setters",
    "CMD_REFACTORING_ARROW_FUNCTION"            : "Convert to Arrow Function",
    "DESCRIPTION_CODE_REFACTORING"              : "Enable/disable JavaScript Code Refactoring",
    "ERROR_TRY_CATCH"                           : "Select valid code to wrap in a Try-catch block",
    "ERROR_WRAP_IN_CONDITION"                   : "Select valid code to wrap in a Condition block",
    "ERROR_ARROW_FUNCTION"                      : "Place the cursor inside a function expression",
    "ERROR_GETTERS_SETTERS"                     : "Place the cursor at a member of an object expression",
    "ERROR_RENAME_MULTICURSOR"                  : "Cannot rename when using multi-cursors",
    "ERROR_RENAME_QUICKEDIT"                    : "Cannot rename this identifier, as it is referenced elsewhere outside this function",
    "ERROR_RENAME_GENERAL"                      : "Cannot rename selected text",

    // extensions/default/JSLint
    "JSLINT_NAME"                               : "JSLint",

    // extensions/default/QuickView
    "CMD_ENABLE_QUICK_VIEW"                     : "Quick View on Hover",

    // extensions/default/RecentProjects
    "CMD_TOGGLE_RECENT_PROJECTS"                : "Recent Projects",

    // extensions/default/MDNDocs
    "DOCS_MORE_LINK"                            : "Read more",

    // extensions/default/CodeFolding
    "COLLAPSE_ALL"                  : "Collapse All",
    "EXPAND_ALL"                    : "Expand All",
    "COLLAPSE_CURRENT"              : "Collapse Current",
    "EXPAND_CURRENT"                : "Expand Current",

    // extensions/default/NavigationAndHistory
    "RECENT_FILES_DLG_HEADER"                    : "Recent Files",
    "RECENT_FILES_DLG_CLEAR_BUTTON_LABEL"        : "Clear",
    "RECENT_FILES_DLG_CLEAR_BUTTON_TITLE"        : "Clear files not in Working Set",

    // Descriptions of core preferences
    "DESCRIPTION_CLOSE_BRACKETS"                     : "true to automatically close braces, brackets and parentheses",
    "DESCRIPTION_CLOSE_OTHERS_ABOVE"                 : "false to remove the \"Close Others Above\" from the Working Files context menu",
    "DESCRIPTION_CLOSE_OTHERS_BELOW"                 : "false to remove the \"Close Others Below\" from the Working Files context menu",
    "DESCRIPTION_CLOSE_OTHERS"                       : "false to remove the \"Close Others\" from the Working Files context menu",
    "DESCRIPTION_CLOSE_TAGS"                         : "Sets the tag closing options",
    "DESCRIPTION_CLOSE_TAGS_DONT_CLOSE_TAGS"         : "An array of tags that should not be auto-closed",
    "DESCRIPTION_CLOSE_TAGS_WHEN_OPENING"            : "Close when > of opening tag is typed",
    "DESCRIPTION_CLOSE_TAGS_WHEN_CLOSING"            : "Close when / of closing tag is typed",
    "DESCRIPTION_CLOSE_TAGS_INDENT_TAGS"             : "An array of tags that when opened has a blank line",
    "DESCRIPTION_CODE_FOLDING_ALWAY_USE_INDENT_FOLD" : "true to always generate collapsible section markers when indent level changes",
    "DESCRIPTION_CODE_FOLDING_ENABLED"               : "true to enable code folding",
    "DESCRIPTION_CODE_FOLDING_HIDE_UNTIL_MOUSEOVER"  : "true to make Section-collapsing markers visible only when you move the mouse over the gutter",
    "DESCRIPTION_CODE_FOLDING_MAX_FOLD_LEVEL"        : "Limits how many levels deep Collapse All applies",
    "DESCRIPTION_CODE_FOLDING_MIN_FOLD_SIZE"         : "Minimum lines before a collapsible section icon appears",
    "DESCRIPTION_CODE_FOLDING_SAVE_FOLD_STATES"      : "true to remember collapsed sections if you close and reopen a file or project",
    "DESCRIPTION_CODE_FOLDING_MAKE_SELECTIONS_FOLDABLE": "true to enable code folding on selected text in the editor",
    "DESCRIPTION_DISABLED_DEFAULT_EXTENSIONS"        : "Default extensions that are disabled",
    "DESCRIPTION_ATTR_HINTS"                         : "Enable/disable HTML attribute hints",
    "DESCRIPTION_CSS_PROP_HINTS"                     : "Enable/disable CSS/LESS/SCSS property hints",
    "DESCRIPTION_JS_HINTS"                           : "Enable/disable JavaScript code hints",
    "DESCRIPTION_JS_HINTS_TYPE_DETAILS"              : "Enable/disable datatype details in JavaScript code hints",
    "DESCRIPTION_PREF_HINTS"                         : "Enable/disable Preferences code hints",
    "DESCRIPTION_SPECIAL_CHAR_HINTS"                 : "Enable/disable HTML entity hints",
    "DESCRIPTION_SVG_HINTS"                          : "Enable/disable SVG code hints",
    "DESCRIPTION_HTML_TAG_HINTS"                     : "Enable/disable HTML tag hints",
    "DESCRIPTION_URL_CODE_HINTS"                     : "Enable/disable URL hints in HTML & CSS/LESS/SCSS",
    "DESCRIPTION_DRAG_DROP_TEXT"                     : "Enable/disable Drag & Drop functionality",
    "DESCRIPTION_HEALTH_DATA_TRACKING"               : "Enable the Health Data Tracking",
    "DESCRIPTION_HIGHLIGHT_MATCHES"                  : "Enables automatic highlighting of matching strings throughout the document",
    "DESCRIPTION_HIGHLIGHT_MATCHES_SHOW_TOKEN"       : "Highlight all strings that match the token the cursor is currently in (no selection needed)",
    "DESCRIPTION_HIGHLIGHT_MATCHES_WORDS_ONLY"       : "Highlight only when selection is a complete token",
    "DESCRIPTION_INSERT_HINT_ON_TAB"                 : "true to insert the currently selected code hint on tab",
    "DESCRIPTION_NO_HINTS_ON_DOT"                    : "true to not automatically show JS code hints when . is typed",
    "DESCRIPTION_JSLINT_OPTIONS"                     : "An object with the default options for JSLint",
    "DESCRIPTION_JSLINT_OPTIONS_ASS"                 : "true to allow assignment expressions",
    "DESCRIPTION_JSLINT_OPTIONS_BITWISE"             : "true to allow bitwise operators",
    "DESCRIPTION_JSLINT_OPTIONS_BROWSER"             : "true if standard browser globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_CLOSURE"             : "true to allow Google Closure idioms",
    "DESCRIPTION_JSLINT_OPTIONS_CONTINUE"            : "true to allow \"continue\" statement",
    "DESCRIPTION_JSLINT_OPTIONS_COUCH"               : "true if CouchDB globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_DEBUG"               : "true to allow debugger statements",
    "DESCRIPTION_JSLINT_OPTIONS_DEVEL"               : "true if browser globals useful in development should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_EQEQ"                : "true to allow == and !=",
    "DESCRIPTION_JSLINT_OPTIONS_ES6"                 : "true if ES6 globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_EVIL"                : "true to allow eval",
    "DESCRIPTION_JSLINT_OPTIONS_FORIN"               : "true to allow unfiltered \"for ... in\"",
    "DESCRIPTION_JSLINT_OPTIONS_INDENT"              : "Set a specific tab width",
    "DESCRIPTION_JSLINT_OPTIONS_MAXERR"              : "The maximum number of warnings reported",
    "DESCRIPTION_JSLINT_OPTIONS_MAXLEN"              : "The maximum number of characters in a line",
    "DESCRIPTION_JSLINT_OPTIONS_NEWCAP"              : "true to allow uncapitalized constructors",
    "DESCRIPTION_JSLINT_OPTIONS_NODE"                : "true if Node.js globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_NOMEN"               : "true to allow dangling underscore in identifiers",
    "DESCRIPTION_JSLINT_OPTIONS_PASSFAIL"            : "true to stop on first error",
    "DESCRIPTION_JSLINT_OPTIONS_PLUSPLUS"            : "true to allow ++ and --",
    "DESCRIPTION_JSLINT_OPTIONS_REGEXP"              : "true to allow . and [^...]. in RegExp",
    "DESCRIPTION_JSLINT_OPTIONS_RHINO"               : "true if Rhino globals should be predefined",
    "DESCRIPTION_JSLINT_OPTIONS_SLOPPY"              : "true to allow missing `use strict` pragma",
    "DESCRIPTION_JSLINT_OPTIONS_STUPID"              : "true if blocking ('...Sync') methods can be used.",
    "DESCRIPTION_JSLINT_OPTIONS_SUB"                 : "true to allow inefficient subscripting",
    "DESCRIPTION_JSLINT_OPTIONS_TODO"                : "true to allow TODO comments",
    "DESCRIPTION_JSLINT_OPTIONS_UNPARAM"             : "true to allow unused parameters",
    "DESCRIPTION_JSLINT_OPTIONS_VARS"                : "true to allow more than 1 vars in a function",
    "DESCRIPTION_JSLINT_OPTIONS_WHITE"               : "true to ignore white-space rules",
    "DESCRIPTION_LANGUAGE"                           : "Language specific settings",
    "DESCRIPTION_LANGUAGE_FILE_EXTENSIONS"           : "Additional mappings from file extension to language name",
    "DESCRIPTION_LANGUAGE_FILE_NAMES"                : "Additional mappings from file name to language name",
    "DESCRIPTION_LINEWISE_COPY_CUT"                  : "Doing copy and cut when there's no selection will copy or cut the whole lines that have cursors in them",
    "DESCRIPTION_INPUT_STYLE"                        : "Selects the way CodeMirror handles input and focus. It can be textarea, which is the default, or contenteditable which is better for screen readers (unstable)",
    "DESCRIPTION_LINTING_ENABLED"                    : "true to enable Code Inspection",
    "DESCRIPTION_ASYNC_TIMEOUT"                      : "The time in milliseconds after which asynchronous linters time out",
    "DESCRIPTION_LINTING_PREFER"                     : "Array of linters to run first",
    "DESCRIPTION_LIVE_DEV_MULTIBROWSER"              : "true to enable experimental Giao diện Trực tiếp",
    "DESCRIPTION_USE_PREFERED_ONLY"                  : "true to run providers specified in linting.prefer only",
    "DESCRIPTION_MAX_CODE_HINTS"                     : "Maximum code hints displayed at once",
    "DESCRIPTION_PATH"                               : "Path specific settings",
    "DESCRIPTION_PROXY"                              : "The URL of the proxy server used for extension installation",
    "DESCRIPTION_SCROLL_PAST_END"                    : "true to enable scrolling beyond the end of the document",
    "DESCRIPTION_SHOW_CODE_HINTS"                    : "false to disable all code hints",
    "DESCRIPTION_SHOW_CURSOR_WHEN_SELECTING"         : "Keeps the blinking cursor visible when you have a text selection",
    "DESCRIPTION_SHOW_LINE_NUMBERS"                  : "true to show line numbers in a “gutter” to the left of the code",
    "DESCRIPTION_SMART_INDENT"                       : "Automatically indent when creating a new block",
    "DESCRIPTION_SOFT_TABS"                          : "false to turn off soft tabs behavior",
    "DESCRIPTION_SORT_DIRECTORIES_FIRST"             : "true to sort the directories first in the project tree",
    "DESCRIPTION_SPACE_UNITS"                        : "Number of spaces to use for space-based indentation",
    "DESCRIPTION_STATIC_SERVER_PORT"                 : "Port number that the built-in server should use for Giao diện Trực tiếp",
    "DESCRIPTION_STYLE_ACTIVE_LINE"                  : "true to highlight background color of the line the cursor is on",
    "DESCRIPTION_TAB_SIZE"                           : "Number of spaces to display for tabs",
    "DESCRIPTION_USE_TAB_CHAR"                       : "true to use tabs instead of spaces",
    "DESCRIPTION_UPPERCASE_COLORS"                   : "true to generate uppercase hex colors in Inline Color Editor",
    "DESCRIPTION_WORD_WRAP"                          : "Wrap lines that exceed the viewport width",
    "DESCRIPTION_SEARCH_AUTOHIDE"                    : "Close the search as soon as the editor is focused",
    "DESCRIPTION_DETECTED_EXCLUSIONS"                : "A list of files that have been detected to cause Tern to run out of control",
    "DESCRIPTION_INFERENCE_TIMEOUT"                  : "The amount of time after which Tern will time out when trying to understand files",
    "DESCRIPTION_SHOW_ERRORS_IN_STATUS_BAR"          : "true to show errors in status bar",
    "DESCRIPTION_QUICK_VIEW_ENABLED"                 : "true to enable Quick View",
    "DESCRIPTION_EXTENSION_LESS_IMAGE_PREVIEW"       : "true to show image previews for URLs missing extensions",
    "DESCRIPTION_THEME"                              : "Select a {APP_NAME} theme",
    "DESCRIPTION_USE_THEME_SCROLLBARS"               : "true to allow custom scroll bars",
    "DESCRIPTION_LINTING_COLLAPSED"                  : "true to collapse linting panel",
    "DESCRIPTION_FONT_FAMILY"                        : "Change font family",
    "DESCRIPTION_FONT_SIZE"                          : "Change font size; e.g. 13px",
    "DESCRIPTION_FIND_IN_FILES_NODE"                 : "true to enable node based search",
    "DESCRIPTION_FIND_IN_FILES_INSTANT"              : "true to enable instant search",
    "DESCRIPTION_FONT_SMOOTHING"                     : "Mac-only: \"subpixel-antialiased\" to enable sub-pixel antialiasing or \"antialiased\" for gray scale antialiasing",
    "DESCRIPTION_OPEN_PREFS_IN_SPLIT_VIEW"           : "false to disable opening preferences file in split view",
    "DESCRIPTION_OPEN_USER_PREFS_IN_SECOND_PANE"     : "false to open user preferences file in left/top pane",
    "DESCRIPTION_MERGE_PANES_WHEN_LAST_FILE_CLOSED"  : "true to collapse panes after the last file from the pane is closed via pane header close button",
    "DESCRIPTION_SHOW_PANE_HEADER_BUTTONS"           : "Toggle when to show the close and flip-view buttons on the header.",
    "DEFAULT_PREFERENCES_JSON_HEADER_COMMENT"        : "/*\n * This is a read-only file with the preferences supported\n * by {APP_NAME}.\n * Use this file as a reference to modify your preferences\n * file \"brackets.json\" opened in the other pane.\n * For more information on how to use preferences inside\n * {APP_NAME}, refer to the web page at https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences\n */",
    "DEFAULT_PREFERENCES_JSON_DEFAULT"               : "Default",
    "DESCRIPTION_PURE_CODING_SURFACE"                : "true to enable code only mode and hide all other UI elements in {APP_NAME}",
    "DESCRIPTION_INDENT_LINE_COMMENT"                : "true to enable indenting of line comments",
    "DESCRIPTION_RECENT_FILES_NAV"                   : "Enable/disable navigation in recent files",
    "DESCRIPTION_LIVEDEV_WEBSOCKET_PORT"             : "Port on which WebSocket Server runs for Giao diện Trực tiếp",
    "DESCRIPTION_LIVE_DEV_HIGHLIGHT_SETTINGS"        : "Giao diện Trực tiếp Highlight settings",
    "DESCRIPTION_LIVEDEV_ENABLE_REVERSE_INSPECT"     : "false to disable Giao diện Trực tiếp reverse inspect",
    
    // Strings for Auto Update
    "DOWNLOAD_FAILED"                                : "Download failed.",
    "DOWNLOAD_COMPLETE"                              : "Download complete!",
    "UPDATE_SUCCESSFUL"                              : "Update successful!",
    "UPDATE_FAILED"                                  : "Update failed!",
    "VALIDATION_FAILED"                              : "Validation failed!",
    "INITIALISATION_FAILED"                          : "Initialization failed!",
    "CLEANUP_FAILED"                                 : "Clean-up failed!",
    "WARNING_TYPE"                                   : "Warning!",
    "CLICK_RESTART_TO_UPDATE"                        : "Click Restart to update Brackets.",
    "UPDATE_ON_NEXT_LAUNCH"                          : "The update will be applied on relaunch.",
    "GO_TO_SITE"                                     : "Go to <a href = \"http://brackets.io/\"> brackets.io </a> to retry.",
    "INTERNET_UNAVAILABLE"                           : "No Internet connection available.",
    "UPDATEDIR_READ_FAILED"                          : "Update directory could not be read.",
    "UPDATEDIR_CLEAN_FAILED"                         : "Update directory could not be cleaned.",
    "INITIAL_DOWNLOAD"                               : "Downloading Update...",
    "RETRY_DOWNLOAD"                                 : "Download failed. Retrying...Attempt ",
    "VALIDATING_INSTALLER"                           : "Download complete! Validating Installer...",
    "CHECKSUM_DID_NOT_MATCH"                         : "Checksum didn't match.",
    "INSTALLER_NOT_FOUND"                            : "Installer not found.",
    "DOWNLOAD_ERROR"                                 : "Error occurred while downloading.",
    "NETWORK_SLOW_OR_DISCONNECTED"                   : "Network is disconnected or too slow.",
    "RESTART_BUTTON"                                 : "Restart",
    "LATER_BUTTON"                                   : "Later",
    "DESCRIPTION_AUTO_UPDATE"                        : "Enable/disable Brackets Auto-update",
    "AUTOUPDATE_ERROR"                               : "Error!",
    "AUTOUPDATE_IN_PROGRESS"                         : "An update is already in progress.",

    "NUMBER_WITH_PERCENTAGE"                         : "{0}%",
    // Strings for Related Files
    "CMD_FIND_RELATED_FILES"                         : "Find Related Files",

    ///String for Php Tooling Extensions
    "PHP_VERSION_INVALID"                            : "Error parsing PHP version. Please check the output of the “php –version” command.",
    "PHP_UNSUPPORTED_VERSION"                        : "Install PHP7 runtime for enabling PHP-related tooling such as Code Hints, Parameter Hints, Jump To Definition and more. Version found: {0}",
    "PHP_EXECUTABLE_NOT_FOUND"                       : "PHP runtime not found. Install the PHP7 runtime and update “executablePath” in PHP Preferences appropriately. This enables PHP-related tooling such as Code Hints, Parameter Hints, Jump To Definition and more.",
    "PHP_PROCESS_SPAWN_ERROR"                        : "Error code {0} encountered while starting the PHP process.",
    "PHP_SERVER_ERROR_TITLE"                         : "Error",
    "PHP_SERVER_MEMORY_LIMIT_INVALID"                : "The memory limit you provided is invalid. Review the PHP preferences to set the correct value.",
    "DESCRIPTION_PHP_TOOLING_CONFIGURATION"          : "PHP Tooling default configuration settings",
    "OPEN_PREFERENNCES"                              : "Open Preferences",

    //Strings for LanguageTools Preferences
    "LANGUAGE_TOOLS_PREFERENCES"                     : "Preferences for Language Tools",

    "FIND_ALL_REFERENCES"                            : "Find All References",
    "REFERENCES_IN_FILES"                            : "references",
    "REFERENCE_IN_FILES"                             : "reference",
    "REFERENCES_NO_RESULTS"                          : "No References available for current cursor position",

    "CMD_FIND_DOCUMENT_SYMBOLS"                      : "Find Document Symbols",
    "CMD_FIND_PROJECT_SYMBOLS"                       : "Find Project Symbols",

   // Remote debugging enabled
    "REMOTE_DEBUGGING_ENABLED"                       : "Remote debugging enabled on localhost:",

   // Remote debugging port argument is invalid
    "REMOTE_DEBUGGING_PORT_INVALID"                  : "Cannot enable remote debugging on port {0}. Port numbers should be between {1} and {2}."
});
